name = "cf-shop"
main = "src/index.js"
compatibility_date = "2023-12-01"

[dev]
port = 8788

[[ d1_databases ]]
binding = "D1_DB"
database_name = "shop_db"
database_id = "bef7ed19-e20a-4531-972b-3a4506f85b6c"